FROM python:3.10

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-warn-script-location --no-cache-dir -r requirements.txt

# Copy the script into the container
COPY . .


# Run the script
CMD ["python", "main.py", "--action", "1"]